/*
 * stamp.js — write src/build-info.js from the current git checkout.
 *
 * WHY THIS EXISTS: the .exe embeds a *copy* of src/ and prompt.js, so "what the
 * repo says" and "what you're running" drift silently. A session once verified
 * 40 effects against a build whose prompt.js predated the other 10, and two
 * builds shipped fatally broken without anyone being able to name the code in
 * them. A build you can't identify is a build you can't debug.
 *
 * Now the titlebar names both halves — the UI's SHA and the app shell's SHA —
 * which are *different* when the app is loading its renderer live off the VM.
 *
 * Generated, not committed (see .gitignore). Regenerated by prestart/presmoke/
 * prescreenshot/prepackage, so any way you launch it, the stamp is current.
 */
'use strict';

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const ROOT = path.join(__dirname, '..');

function git(args, fallback) {
  try {
    return execFileSync('git', args, { cwd: ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
  } catch { return fallback; }
}

// Only this app's files count: a dirty simjim/ tree next door isn't a dirty
// Flourish build, and flagging it as one would train us to ignore the flag.
const dirty = git(['status', '--porcelain', '--', ROOT], '') !== '';
const sha = git(['rev-parse', '--short', 'HEAD'], 'nogit');
const branch = git(['rev-parse', '--abbrev-ref', 'HEAD'], '?');
const stampedAt = new Date().toISOString();

const info = { sha, branch, dirty, stampedAt };

const out = `/* GENERATED by tools/stamp.js — do not edit, do not commit. */
window.FLOURISH_BUILD = ${JSON.stringify(info)};
`;

fs.writeFileSync(path.join(ROOT, 'src', 'build-info.js'), out, 'utf8');

// The main process needs the same stamp, and it can't read build-info.js
// (that's renderer scope) or run git (a packaged .exe has no repo).
fs.writeFileSync(
  path.join(ROOT, 'build-info.json'),
  JSON.stringify(info, null, 2) + '\n',
  'utf8'
);

console.log(`stamped ${sha}${dirty ? '+dirty' : ''} (${branch})`);
